import { useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { CREATORS, hydrateCreatorsFromDB, useCreatorsVersion } from "@/lib/creator-partnerships";
import { secondLookAction } from "@/lib/creators.functions";
export function SecondLookPanel() {
 const version=useCreatorsVersion(); const act=useServerFn(secondLookAction); const [open,setOpen]=useState(false); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 const creators=useMemo(()=>{void version;return CREATORS.filter(c=>Boolean(c.outreachSecondLookAt)&&c.sethApprovalStatus==="approved"&&!c.outreachSentAt).sort((a,b)=>(b.outreachSecondLookAt??"").localeCompare(a.outreachSecondLookAt??""));},[version]);
 const restore=async(id:string)=>{setBusy(id);setError(null);try{const result=await act({data:{id,action:"restore"}});if(!result?.ok)throw new Error("Server did not confirm restore");await hydrateCreatorsFromDB();}catch(e){setError(e instanceof Error?e.message:"Could not restore");}finally{setBusy(null);}};
 return <section className="overflow-hidden rounded-xl border border-amber-500 bg-card"><button type="button" onClick={()=>setOpen(v=>!v)} className="flex w-full items-center gap-3 px-4 py-4 text-left"><span>{open?"▼":"▶"}</span><span className="flex-1 font-semibold">Second Look — Seth Review ({creators.length})<span className="block text-xs font-normal text-muted-foreground">Deferred by outreach team, separate from Needs Manual Review</span></span><span className="rounded border px-3 py-1 text-sm">{open?"Close":"Open"}</span></button>{open&&<div className="space-y-2 border-t p-3">{error&&<p role="alert" className="text-red-700">{error}</p>}{creators.length===0?<p className="text-sm">No creators awaiting a second look.</p>:creators.map(c=><div key={c.id} className="flex flex-wrap items-center gap-2 rounded-lg border p-3"><a className="min-w-0 flex-1 underline" href={c.tiktok??undefined} target="_blank" rel="noopener noreferrer">{c.name}</a><button disabled={busy===c.id} onClick={()=>void restore(c.id)} className="rounded border px-3 py-2 text-sm disabled:opacity-50">Return to Queue</button></div>)}</div>}</section>;
}
