/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamActionsRouteImport } from './routes/team-actions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ReviewedSurvivalTabsMreRouteImport } from './routes/reviewed-survival-tabs-mre'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmazonDiscoveryRouteImport } from './routes/amazon-discovery'
import { Route as AmazonCreatorsRouteImport } from './routes/amazon-creators'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge.$id'
import { Route as CreatorsIdRouteImport } from './routes/creators.$id'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamActionsRoute = TeamActionsRouteImport.update({
  id: '/team-actions',
  path: '/team-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewedSurvivalTabsMreRoute = ReviewedSurvivalTabsMreRouteImport.update({
  id: '/reviewed-survival-tabs-mre',
  path: '/reviewed-survival-tabs-mre',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonDiscoveryRoute = AmazonDiscoveryRouteImport.update({
  id: '/amazon-discovery',
  path: '/amazon-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonCreatorsRoute = AmazonCreatorsRouteImport.update({
  id: '/amazon-creators',
  path: '/amazon-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeRoute,
} as any)
const CreatorsIdRoute = CreatorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CreatorsRoute,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amazon-creators': typeof AmazonCreatorsRoute
  '/amazon-discovery': typeof AmazonDiscoveryRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/comments': typeof CommentsRoute
  '/communications': typeof CommunicationsRoute
  '/content': typeof ContentRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/decisions': typeof DecisionsRoute
  '/email': typeof EmailRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/leads': typeof LeadsRoute
  '/review': typeof ReviewRoute
  '/reviewed-survival-tabs-mre': typeof ReviewedSurvivalTabsMreRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/team-actions': typeof TeamActionsRoute
  '/templates': typeof TemplatesRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/assets/$id': typeof AssetsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amazon-creators': typeof AmazonCreatorsRoute
  '/amazon-discovery': typeof AmazonDiscoveryRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/comments': typeof CommentsRoute
  '/communications': typeof CommunicationsRoute
  '/content': typeof ContentRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/decisions': typeof DecisionsRoute
  '/email': typeof EmailRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/leads': typeof LeadsRoute
  '/review': typeof ReviewRoute
  '/reviewed-survival-tabs-mre': typeof ReviewedSurvivalTabsMreRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/team-actions': typeof TeamActionsRoute
  '/templates': typeof TemplatesRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/assets/$id': typeof AssetsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/amazon-creators': typeof AmazonCreatorsRoute
  '/amazon-discovery': typeof AmazonDiscoveryRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRoute
  '/assets': typeof AssetsRouteWithChildren
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/comments': typeof CommentsRoute
  '/communications': typeof CommunicationsRoute
  '/content': typeof ContentRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/decisions': typeof DecisionsRoute
  '/email': typeof EmailRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/leads': typeof LeadsRoute
  '/review': typeof ReviewRoute
  '/reviewed-survival-tabs-mre': typeof ReviewedSurvivalTabsMreRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/team-actions': typeof TeamActionsRoute
  '/templates': typeof TemplatesRoute
  '/video': typeof VideoRoute
  '/website': typeof WebsiteRoute
  '/assets/$id': typeof AssetsIdRoute
  '/creators/$id': typeof CreatorsIdRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/amazon-creators'
    | '/amazon-discovery'
    | '/analytics'
    | '/archive'
    | '/assets'
    | '/auth'
    | '/campaigns'
    | '/comments'
    | '/communications'
    | '/content'
    | '/creators'
    | '/decisions'
    | '/email'
    | '/knowledge'
    | '/leads'
    | '/review'
    | '/reviewed-survival-tabs-mre'
    | '/seo'
    | '/settings'
    | '/team-actions'
    | '/templates'
    | '/video'
    | '/website'
    | '/assets/$id'
    | '/creators/$id'
    | '/knowledge/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/amazon-creators'
    | '/amazon-discovery'
    | '/analytics'
    | '/archive'
    | '/assets'
    | '/auth'
    | '/campaigns'
    | '/comments'
    | '/communications'
    | '/content'
    | '/creators'
    | '/decisions'
    | '/email'
    | '/knowledge'
    | '/leads'
    | '/review'
    | '/reviewed-survival-tabs-mre'
    | '/seo'
    | '/settings'
    | '/team-actions'
    | '/templates'
    | '/video'
    | '/website'
    | '/assets/$id'
    | '/creators/$id'
    | '/knowledge/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/amazon-creators'
    | '/amazon-discovery'
    | '/analytics'
    | '/archive'
    | '/assets'
    | '/auth'
    | '/campaigns'
    | '/comments'
    | '/communications'
    | '/content'
    | '/creators'
    | '/decisions'
    | '/email'
    | '/knowledge'
    | '/leads'
    | '/review'
    | '/reviewed-survival-tabs-mre'
    | '/seo'
    | '/settings'
    | '/team-actions'
    | '/templates'
    | '/video'
    | '/website'
    | '/assets/$id'
    | '/creators/$id'
    | '/knowledge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AmazonCreatorsRoute: typeof AmazonCreatorsRoute
  AmazonDiscoveryRoute: typeof AmazonDiscoveryRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchiveRoute: typeof ArchiveRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  CommentsRoute: typeof CommentsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ContentRoute: typeof ContentRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  DecisionsRoute: typeof DecisionsRoute
  EmailRoute: typeof EmailRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  ReviewRoute: typeof ReviewRoute
  ReviewedSurvivalTabsMreRoute: typeof ReviewedSurvivalTabsMreRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  TeamActionsRoute: typeof TeamActionsRoute
  TemplatesRoute: typeof TemplatesRoute
  VideoRoute: typeof VideoRoute
  WebsiteRoute: typeof WebsiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-actions': {
      id: '/team-actions'
      path: '/team-actions'
      fullPath: '/team-actions'
      preLoaderRoute: typeof TeamActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewed-survival-tabs-mre': {
      id: '/reviewed-survival-tabs-mre'
      path: '/reviewed-survival-tabs-mre'
      fullPath: '/reviewed-survival-tabs-mre'
      preLoaderRoute: typeof ReviewedSurvivalTabsMreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon-discovery': {
      id: '/amazon-discovery'
      path: '/amazon-discovery'
      fullPath: '/amazon-discovery'
      preLoaderRoute: typeof AmazonDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon-creators': {
      id: '/amazon-creators'
      path: '/amazon-creators'
      fullPath: '/amazon-creators'
      preLoaderRoute: typeof AmazonCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/creators/$id': {
      id: '/creators/$id'
      path: '/$id'
      fullPath: '/creators/$id'
      preLoaderRoute: typeof CreatorsIdRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface CreatorsRouteChildren {
  CreatorsIdRoute: typeof CreatorsIdRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsIdRoute: CreatorsIdRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeIdRoute: typeof KnowledgeIdRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeIdRoute: KnowledgeIdRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AmazonCreatorsRoute: AmazonCreatorsRoute,
  AmazonDiscoveryRoute: AmazonDiscoveryRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchiveRoute: ArchiveRoute,
  AssetsRoute: AssetsRouteWithChildren,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  CommentsRoute: CommentsRoute,
  CommunicationsRoute: CommunicationsRoute,
  ContentRoute: ContentRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  DecisionsRoute: DecisionsRoute,
  EmailRoute: EmailRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LeadsRoute: LeadsRoute,
  ReviewRoute: ReviewRoute,
  ReviewedSurvivalTabsMreRoute: ReviewedSurvivalTabsMreRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  TeamActionsRoute: TeamActionsRoute,
  TemplatesRoute: TemplatesRoute,
  VideoRoute: VideoRoute,
  WebsiteRoute: WebsiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
